- name: Configuration de l'infrastructure Multi-Tiers
  hosts: all
  become: true
  vars:
    # Variables globales pour la cohérence
    db_host: "192.168.56.22"
    db_name: "balrog_db"
    db_user: "balrog_user"
    db_pass: "balrog_password"
    back_ip: "127.0.0.1" # réseau local car on est dans le browser (sur l'hote)
    pgadmin_email: "admin@admin.com"
    pgadmin_pass: "password123"
    backup_file_host: "./init_db/app_2023_04_03_12_58_18.backup"
    backup_file_dest: "/tmp/db_restore.backup"

  tasks:
    # --- SECTION FRONTEND ---
    - name: "[Frontend] Installer Node.js et NPM"
      apt: { name: [nodejs, npm], state: present }
      when: inventory_hostname == 'frontend'

    - name: "[Frontend] Cloner le dépôt balrog-js"
      git:
        repo: 'https://github.com/phil-form/balrog-js'
        dest: /home/vagrant/frontend
        force: yes
      when: inventory_hostname == 'frontend'

    - name: "[Frontend] Configurer l'IP du Backend dans le code"
      replace:
        path: /home/vagrant/frontend/src/env/environement.ts # Ajustez le fichier cible si nécessaire
        regexp: '#@#\{BACK_IP\}#@#'
        replace: "{{ back_ip }}"
      when: inventory_hostname == 'frontend'

    - name: "[Frontend] Installer les dépendances et démarrer"
      shell: |
        npm install
        nohup npm start > /dev/null 2>&1 &
      args:
        # Je me déplace dans le dossier frontend
        chdir: /home/vagrant/frontend
      when: inventory_hostname == 'frontend'

    # --- SECTION BACKEND ---
    - name: "[Backend] Installer Node.js et NPM"
      apt: { name: [nodejs, npm], state: present }
      when: inventory_hostname == 'backend'

    - name: "[Backend] Cloner le dépôt backend"
      git:
        repo: 'https://github.com/phil-form/backend'
        dest: /home/vagrant/backend
        force: yes
      when: inventory_hostname == 'backend'

    - name: "[Backend] Configuration des variables DB dans le code"
      replace:
        path: "/home/vagrant/backend/src/{{ item.file }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { file: 'data-source.ts', regexp: '#@#\{DB_HOST\}#@#', replace: "{{ db_host }}" }
        - { file: 'data-source.ts', regexp: '#@#\{DB_USER\}#@#', replace: "{{ db_user }}" }
        - { file: 'data-source.ts', regexp: '#@#\{DB_PASSWORD\}#@#', replace: "{{ db_pass }}" }
        - { file: 'data-source.ts', regexp: '#@#\{DB_NAME\}#@#', replace: "{{ db_name }}" }
      when: inventory_hostname == 'backend'

    - name: "[Backend] Installer les dépendances et migrer la db"
      shell: |
        npm install
        npm run migrate
      args:
        chdir: /home/vagrant/backend
      when: inventory_hostname == 'backend'

    - name: "[Backend] Installer les dépendances et démarrer"
      shell: |
        npm install
        nohup npm start > /dev/null 2>&1 &
      args:
        chdir: /home/vagrant/backend
      when: inventory_hostname == 'backend'

    # --- SECTION DATABASE & PGADMIN ---
    - name: "[DB] Installer PostgreSQL et dépendances Python"
      apt: { name: [postgresql, postgresql-contrib, python3-psycopg2, curl, gnupg], state: present }
      when: inventory_hostname == 'database'

    - name: "[DB] Configurer PostgreSQL pour écouter sur le réseau"
      lineinfile:
        path: /etc/postgresql/17/main/postgresql.conf
        regexp: "^#listen_addresses"
        line: "listen_addresses = '*'"
      when: inventory_hostname == 'database'
      notify: restart postgres

    - name: "[DB] Sécuriser pg_hba.conf (Autoriser Backend uniquement)"
      lineinfile:
        path: /etc/postgresql/17/main/pg_hba.conf
        line: "host all all 192.168.56.21/32 scram-sha-256"
      when: inventory_hostname == 'database'
      notify: restart postgres

    - name: "[DB] Créer la base et l'utilisateur"
      become_user: postgres
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        role_attr_flags: "SUPERUSER"
        state: present
      when: inventory_hostname == 'database'

    - name: "[DB] Créer la DB physique"
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
      when: inventory_hostname == 'database'

    - name: "[ DB ] Copier le fichier de backup sur la VM"
      copy:
        src: "{{ backup_file_host }}"
        dest: "{{ backup_file_dest }}"
        owner: postgres # On donne les droits au user postgres tout de suite
      when: inventory_hostname == 'database'

    - name: "[ DB ] Restaurer la base de données (pg_restore)"
      become_user: postgres
      shell: >
        pg_restore 
        --dbname={{ db_name }} 
        --no-owner 
        --role={{ db_user }} 
        {{ backup_file_dest }}
      when: inventory_hostname == 'database'
      args:
        creates: /var/lib/postgresql/restore_done.flag

    - name: "[ DB ] Marquer la restauration comme terminée"
      file:
        path: /var/lib/postgresql/restore_done.flag
        state: touch
      when: inventory_hostname == 'database'

    - name: "[ DB ] Nettoyer le fichier de backup"
      file:
        path: "{{ backup_file_dest }}"
        state: absent
      when: inventory_hostname == 'database'

    - name: "[ pgAdmin ] Ajouter le dépôt (télécharger la clé gpg)"
      shell: |
        curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
      when: inventory_hostname == 'database'
      args:
        creates: /usr/share/keyrings/packages-pgadmin-org.gpg

    - name: "[ pgAdmin ] Ajouter le dépôt (créer le source.list)"
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/trixie pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list
      when: inventory_hostname == 'database'
      args:
        creates: /etc/apt/sources.list.d/pgadmin4.list

    - name: "[pgAdmin] Installer pgAdmin4-web"
      apt: { name: pgadmin4-web, state: present, update_cache: yes }
      when: inventory_hostname == 'database'

    - name: "[pgAdmin] Configuration automatique du mode Web"
      environment:
        PGADMIN_SETUP_EMAIL: "{{ pgadmin_email }}"
        PGADMIN_SETUP_PASSWORD: "{{ pgadmin_pass }}"
      shell: "/usr/pgadmin4/bin/setup-web.sh --yes"
      args:
        creates: /etc/apache2/conf-enabled/pgadmin4.conf
      when: inventory_hostname == 'database'

    # AJOUTE CECI ICI pour forcer le redémarrage AVANT la suite
    - name: Redémarrer PostgreSQL pour appliquer les changements
      service: { name: postgresql, state: restarted }
      when: inventory_hostname == 'database'

  handlers:
    - name: restart postgres
      service: { name: postgresql, state: restarted }
